### ISSUE TITLE
Request: Please publish 0.2.1

### ISSUE THREAD

**Issue by gmlewis** [yj-qin/regexp#10]
Hi, and thank you for this excellent package!
Could you please publish it so that I can use it here:
https://github.com/gmlewis/moonbit-fonts
?
Thanks again!

**Comment by yj-qin** [comment]
Hi, Glenn. Thank you for your interest in this package! 
I just publish the 0.2.1 version, please take a look and welcome your feedback.

**Comment by gmlewis** [comment]
> Hi, Glenn. Thank you for your interest in this package! I just publish the 0.2.1 version, please take a look and welcome your feedback.

Thank you!
