### ISSUE TITLE
Warning: Deprecated string interpolation syntax. Use `\{ ... }` instead.

### ISSUE THREAD

**Issue by oboard** [yj-qin/regexp#12]
[1025] Warning: Warning: Deprecated string interpolation syntax. Use `\{ ... }` instead.
    ╭─[/Users/oboard/Development/moonbit-packages/mocket/.mooncakes/yj-qin/regexp/ast.mbt:25:40]
    │
 25 │       Some(max) => if min == max { "{\(min)} " } else { "{\(min),\(max)} " }
    │                                        ─┬─  
    │                                         ╰─── Warning: Deprecated string interpolation syntax. Use `\{ ... }` instead.
────╯
[1025] Warning: Warning: Deprecated string interpolation syntax. Use `\{ ... }` instead.
    ╭─[/Users/oboard/Development/moonbit-packages/mocket/.mooncakes/yj-qin/regexp/ast.mbt:25:61]
    │
 25 │       Some(max) => if min == max { "{\(min)} " } else { "{\(min),\(max)} " }
    │                                                             ─┬─  
    │                                                              ╰─── Warning: Deprecated string interpolation syntax. Use `\{ ... }` instead.
────╯

**Comment by yj-qin** [comment]
Fixed. Thanks for your feedback!
